import { make_keyword } from "./helpers.js";

// Every keyword the grammar references, and nothing else. A keyword only
// wins over an identifier in a parse state where that keyword is valid
// (`word: $._identifier` in grammar.js turns on keyword extraction), which
// is what lets Snowflake's large non-reserved vocabulary — NAME, TYPE,
// VALUE, STATUS, HANDLER, RUNTIME_VERSION, WAREHOUSE_SIZE, ... — stay
// usable as column names. Option and parameter names are deliberately not
// keywords; they are identifiers (see grammar/column-lists.js, `option`).
export default {

  // DML and query shape
  keyword_select: _ => make_keyword("select"),
  keyword_delete: _ => make_keyword("delete"),
  keyword_insert: _ => make_keyword("insert"),
  keyword_update: _ => make_keyword("update"),
  keyword_merge: _ => make_keyword("merge"),
  keyword_into: _ => make_keyword("into"),
  keyword_values: _ => make_keyword("values"),
  keyword_matched: _ => make_keyword("matched"),
  keyword_just: _ => make_keyword("just"),
  keyword_set: _ => make_keyword("set"),
  keyword_unset: _ => make_keyword("unset"),
  keyword_from: _ => make_keyword("from"),
  keyword_where: _ => make_keyword("where"),
  keyword_group: _ => make_keyword("group"),
  keyword_by: _ => make_keyword("by"),
  keyword_having: _ => make_keyword("having"),
  keyword_qualify: _ => make_keyword("qualify"),
  keyword_order: _ => make_keyword("order"),
  keyword_asc: _ => make_keyword("asc"),
  keyword_desc: _ => make_keyword("desc"),
  keyword_nulls: _ => make_keyword("nulls"),
  keyword_first: _ => make_keyword("first"),
  keyword_last: _ => make_keyword("last"),
  keyword_distinct: _ => make_keyword("distinct"),
  keyword_all: _ => make_keyword("all"),
  keyword_top: _ => make_keyword("top"),
  keyword_with: _ => make_keyword("with"),
  keyword_as: _ => make_keyword("as"),
  keyword_union: _ => make_keyword("union"),
  keyword_except: _ => make_keyword("except"),
  keyword_minus: _ => make_keyword("minus"),
  keyword_intersect: _ => make_keyword("intersect"),
  keyword_offset: _ => make_keyword("offset"),
  keyword_limit: _ => make_keyword("limit"),
  keyword_recursive: _ => make_keyword("recursive"),
  keyword_roles: _ => make_keyword("roles"),
  keyword_option: _ => make_keyword("option"),
  keyword_pattern: _ => make_keyword("pattern"),
  keyword_overwrite: _ => make_keyword("overwrite"),
  keyword_pivot: _ => make_keyword("pivot"),
  keyword_unpivot: _ => make_keyword("unpivot"),
  keyword_exclude: _ => make_keyword("exclude"),
  keyword_rename: _ => make_keyword("rename"),
  keyword_grouping: _ => make_keyword("grouping"),
  keyword_sets: _ => make_keyword("sets"),
  keyword_cube: _ => make_keyword("cube"),
  keyword_rollup: _ => make_keyword("rollup"),
  keyword_window: _ => make_keyword("window"),
  keyword_within: _ => make_keyword("within"),

  // Joins
  keyword_join: _ => make_keyword("join"),
  keyword_inner: _ => make_keyword("inner"),
  keyword_left: _ => make_keyword("left"),
  keyword_right: _ => make_keyword("right"),
  keyword_full: _ => make_keyword("full"),
  keyword_outer: _ => make_keyword("outer"),
  keyword_cross: _ => make_keyword("cross"),
  keyword_on: _ => make_keyword("on"),
  keyword_off: _ => make_keyword("off"),
  keyword_using: _ => make_keyword("using"),
  keyword_lateral: _ => make_keyword("lateral"),

  // Expressions
  keyword_case: _ => make_keyword("case"),
  keyword_when: _ => make_keyword("when"),
  keyword_then: _ => make_keyword("then"),
  keyword_else: _ => make_keyword("else"),
  keyword_end: _ => make_keyword("end"),
  keyword_in: _ => make_keyword("in"),
  keyword_and: _ => make_keyword("and"),
  keyword_or: _ => make_keyword("or"),
  keyword_is: _ => make_keyword("is"),
  keyword_not: _ => make_keyword("not"),
  keyword_like: _ => make_keyword("like"),
  keyword_ilike: _ => make_keyword("ilike"),
  keyword_between: _ => make_keyword("between"),
  keyword_exists: _ => make_keyword("exists"),
  keyword_cast: _ => make_keyword("cast"),
  keyword_try_cast: _ => make_keyword("try_cast"),
  keyword_collate: _ => make_keyword("collate"),
  keyword_null: _ => make_keyword("null"),
  keyword_true: _ => make_keyword("true"),
  keyword_false: _ => make_keyword("false"),
  keyword_interval: _ => make_keyword("interval"),
  keyword_identifier: _ => make_keyword("identifier"),
  keyword_regexp: _ => make_keyword("regexp"),
  keyword_rlike: _ => make_keyword("rlike"),

  // Window functions
  keyword_over: _ => make_keyword("over"),
  keyword_partition: _ => make_keyword("partition"),
  keyword_range: _ => make_keyword("range"),
  keyword_rows: _ => make_keyword("rows"),
  keyword_unbounded: _ => make_keyword("unbounded"),
  keyword_preceding: _ => make_keyword("preceding"),
  keyword_following: _ => make_keyword("following"),
  keyword_current: _ => make_keyword("current"),

  // Snowflake Scripting
  keyword_begin: _ => make_keyword("begin"),
  keyword_declare: _ => make_keyword("declare"),
  keyword_let: _ => make_keyword("let"),
  keyword_if: _ => make_keyword("if"),
  keyword_elseif: _ => make_keyword("elseif"),
  keyword_while: _ => make_keyword("while"),
  keyword_do: _ => make_keyword("do"),
  keyword_for: _ => make_keyword("for"),
  keyword_repeat: _ => make_keyword("repeat"),
  keyword_until: _ => make_keyword("until"),
  keyword_loop: _ => make_keyword("loop"),
  keyword_break: _ => choice(make_keyword("break"), make_keyword("exit")),
  keyword_continue: _ => choice(make_keyword("continue"), make_keyword("iterate")),
  keyword_return: _ => make_keyword("return"),
  keyword_exception: _ => make_keyword("exception"),
  keyword_raise: _ => make_keyword("raise"),
  keyword_cursor: _ => make_keyword("cursor"),
  keyword_open: _ => make_keyword("open"),
  keyword_close: _ => make_keyword("close"),
  keyword_fetch: _ => make_keyword("fetch"),
  keyword_next: _ => make_keyword("next"),
  keyword_resultset: _ => make_keyword("resultset"),
  keyword_execute: _ => make_keyword("execute"),
  keyword_immediate: _ => make_keyword("immediate"),
  keyword_to: _ => make_keyword("to"),
  keyword_reverse: _ => make_keyword("reverse"),
  keyword_other: _ => make_keyword("other"),

  // DDL verbs and object kinds
  keyword_create: _ => make_keyword("create"),
  keyword_or: _ => make_keyword("or"),
  keyword_replace: _ => make_keyword("replace"),
  keyword_alter: _ => make_keyword("alter"),
  keyword_drop: _ => make_keyword("drop"),
  keyword_add: _ => make_keyword("add"),
  keyword_column: _ => make_keyword("column"),
  keyword_modify: _ => make_keyword("modify"),
  keyword_table: _ => make_keyword("table"),
  keyword_view: _ => make_keyword("view"),
  keyword_materialized: _ => make_keyword("materialized"),
  keyword_dynamic: _ => make_keyword("dynamic"),
  keyword_secure: _ => make_keyword("secure"),
  keyword_transient: _ => make_keyword("transient"),
  keyword_temporary: _ => choice(make_keyword("temp"), make_keyword("temporary")),
  keyword_volatile: _ => make_keyword("volatile"),
  keyword_external: _ => make_keyword("external"),
  keyword_if: _ => make_keyword("if"),
  keyword_exists: _ => make_keyword("exists"),
  keyword_cluster: _ => make_keyword("cluster"),
  keyword_data: _ => make_keyword("data"),
  keyword_type: _ => make_keyword("type"),
  keyword_suspended: _ => make_keyword("suspended"),
  keyword_enable: _ => make_keyword("enable"),
  keyword_disable: _ => make_keyword("disable"),
  keyword_failsafe: _ => make_keyword("failsafe"),
  keyword_refresh: _ => make_keyword("refresh"),
  keyword_granted: _ => make_keyword("granted"),
  keyword_procedure: _ => make_keyword("procedure"),
  keyword_function: _ => make_keyword("function"),
  keyword_returns: _ => make_keyword("returns"),
  keyword_language: _ => make_keyword("language"),
  keyword_task: _ => make_keyword("task"),
  keyword_stage: _ => make_keyword("stage"),
  keyword_file: _ => make_keyword("file"),
  keyword_format: _ => make_keyword("format"),
  keyword_stream: _ => make_keyword("stream"),
  keyword_pipe: _ => make_keyword("pipe"),
  keyword_warehouse: _ => make_keyword("warehouse"),
  keyword_database: _ => make_keyword("database"),
  keyword_schema: _ => make_keyword("schema"),
  keyword_role: _ => make_keyword("role"),
  keyword_user: _ => make_keyword("user"),
  keyword_sequence: _ => make_keyword("sequence"),
  keyword_tag: _ => make_keyword("tag"),
  keyword_agent: _ => make_keyword("agent"),
  keyword_cortex: _ => make_keyword("cortex"),
  keyword_service: _ => make_keyword("service"),
  keyword_streamlit: _ => make_keyword("streamlit"),
  keyword_extract: _ => make_keyword("extract"),
  keyword_specification: _ => make_keyword("specification"),
  keyword_integration: _ => make_keyword("integration"),
  keyword_storage: _ => make_keyword("storage"),
  keyword_api: _ => make_keyword("api"),
  keyword_security: _ => make_keyword("security"),
  keyword_notification: _ => make_keyword("notification"),
  keyword_access: _ => make_keyword("access"),
  keyword_clone: _ => make_keyword("clone"),
  keyword_swap: _ => make_keyword("swap"),
  keyword_resume: _ => make_keyword("resume"),
  keyword_suspend: _ => make_keyword("suspend"),
  keyword_abort: _ => make_keyword("abort"),
  keyword_queries: _ => make_keyword("queries"),
  keyword_copy: _ => make_keyword("copy"),
  keyword_grants: _ => make_keyword("grants"),
  keyword_masking: _ => make_keyword("masking"),
  keyword_policy: _ => make_keyword("policy"),
  keyword_search: _ => make_keyword("search"),
  keyword_optimization: _ => make_keyword("optimization"),
  keyword_row: _ => make_keyword("row"),
  keyword_comment: _ => make_keyword("comment"),

  // Constraint suffixes
  keyword_constraint: _ => make_keyword("constraint"),
  keyword_primary: _ => make_keyword("primary"),
  keyword_key: _ => make_keyword("key"),
  keyword_unique: _ => make_keyword("unique"),
  keyword_foreign: _ => make_keyword("foreign"),
  keyword_references: _ => make_keyword("references"),
  keyword_check: _ => make_keyword("check"),
  keyword_enforced: _ => make_keyword("enforced"),
  keyword_rely: _ => make_keyword("rely"),
  keyword_no: _ => make_keyword("no"),
  keyword_cascade: _ => make_keyword("cascade"),
  keyword_restrict: _ => make_keyword("restrict"),
  keyword_default: _ => make_keyword("default"),
  keyword_autoincrement: _ => choice(make_keyword("autoincrement"), make_keyword("identity")),
  keyword_initially: _ => make_keyword("initially"),
  keyword_suspended: _ => make_keyword("suspended"),

  // Grants
  keyword_grant: _ => make_keyword("grant"),
  keyword_revoke: _ => make_keyword("revoke"),
  keyword_privileges: _ => make_keyword("privileges"),
  keyword_future: _ => make_keyword("future"),
  keyword_share: _ => make_keyword("share"),
  keyword_public: _ => make_keyword("public"),
  keyword_imported: _ => make_keyword("imported"),
  keyword_ownership: _ => make_keyword("ownership"),
  keyword_modify: _ => make_keyword("modify"),
  keyword_usage: _ => make_keyword("usage"),
  keyword_monitor: _ => make_keyword("monitor"),
  keyword_operate: _ => make_keyword("operate"),
  keyword_evolve: _ => make_keyword("evolve"),

  // Procedure/function execution context
  keyword_execute_as: _ => make_keyword("execute"),
  keyword_caller: _ => make_keyword("caller"),
  keyword_owner: _ => make_keyword("owner"),
  keyword_sql: _ => make_keyword("sql"),
  keyword_javascript: _ => make_keyword("javascript"),
  keyword_python: _ => make_keyword("python"),
  keyword_java: _ => make_keyword("java"),
  keyword_scala: _ => make_keyword("scala"),

  // Staging and transfer
  keyword_put: _ => make_keyword("put"),
  keyword_get: _ => make_keyword("get"),
  keyword_list: _ => make_keyword("list"),
  keyword_remove: _ => make_keyword("remove"),

  // Admin
  keyword_use: _ => make_keyword("use"),
  keyword_secondary: _ => make_keyword("secondary"),
  keyword_call: _ => make_keyword("call"),
  keyword_show: _ => make_keyword("show"),
  keyword_describe: _ => choice(make_keyword("describe"), make_keyword("desc")),
  keyword_terse: _ => make_keyword("terse"),
  keyword_history: _ => make_keyword("history"),
  keyword_start: _ => make_keyword("start"),
  keyword_increment: _ => make_keyword("increment"),
  keyword_transaction: _ => make_keyword("transaction"),
  keyword_work: _ => make_keyword("work"),
  keyword_commit: _ => make_keyword("commit"),
  keyword_rollback: _ => make_keyword("rollback"),
  keyword_session: _ => make_keyword("session"),
  keyword_global: _ => make_keyword("global"),
  keyword_account: _ => make_keyword("account"),
  keyword_starts: _ => make_keyword("starts"),
  keyword_none: _ => make_keyword("none"),

  // MATCH_RECOGNIZE
  keyword_semantic: _ => make_keyword("semantic"),
  keyword_tables: _ => make_keyword("tables"),
  keyword_relationships: _ => make_keyword("relationships"),
  keyword_facts: _ => make_keyword("facts"),
  keyword_dimensions: _ => make_keyword("dimensions"),
  keyword_metrics: _ => make_keyword("metrics"),
  keyword_ai_verified_queries: _ => make_keyword("ai_verified_queries"),
  keyword_match_recognize: _ => make_keyword("match_recognize"),
  keyword_match: _ => make_keyword("match"),
  keyword_recognize: _ => make_keyword("recognize"),
  keyword_measures: _ => make_keyword("measures"),
  keyword_per: _ => make_keyword("per"),
  keyword_past: _ => make_keyword("past"),
  keyword_skip: _ => make_keyword("skip"),
  keyword_truncate: _ => make_keyword("truncate"),
  keyword_define: _ => make_keyword("define"),
  keyword_after: _ => make_keyword("after"),
  keyword_schedule: _ => make_keyword("schedule"),

  // Types
  keyword_number: _ => choice(make_keyword("number"), make_keyword("numeric"), make_keyword("decimal"), make_keyword("dec")),
  keyword_int: _ => choice(make_keyword("int"), make_keyword("integer"), make_keyword("bigint"), make_keyword("smallint"), make_keyword("tinyint"), make_keyword("byteint")),
  keyword_float: _ => choice(make_keyword("float"), make_keyword("float4"), make_keyword("float8"), make_keyword("real")),
  keyword_double: _ => seq(make_keyword("double"), make_keyword("precision")),
  keyword_double_prec_only: _ => make_keyword("double"),
  keyword_boolean: _ => make_keyword("boolean"),
  keyword_char: _ => choice(make_keyword("char"), make_keyword("character"), make_keyword("nchar")),
  keyword_varchar: _ => choice(make_keyword("varchar"), make_keyword("nvarchar"), make_keyword("nvarchar2"), make_keyword("varchar2")),
  keyword_string: _ => choice(make_keyword("string"), make_keyword("text")),
  keyword_binary: _ => choice(make_keyword("binary"), make_keyword("varbinary")),
  keyword_date: _ => make_keyword("date"),
  keyword_datetime: _ => make_keyword("datetime"),
  keyword_time: _ => make_keyword("time"),
  keyword_timestamp: _ => choice(make_keyword("timestamp"), make_keyword("timestamp_ntz"), make_keyword("timestamp_ltz"), make_keyword("timestamp_tz")),
  keyword_variant: _ => make_keyword("variant"),
  keyword_object: _ => make_keyword("object"),
  keyword_array: _ => make_keyword("array"),
  keyword_geography: _ => make_keyword("geography"),
  keyword_geometry: _ => make_keyword("geometry"),
  keyword_vector: _ => make_keyword("vector"),
};
